### ISSUE TITLE
 Build the project manually 

### ISSUE THREAD

**Issue by alt3kx** [BishopFox/rmiscout#2] opened 2020-06-04 04:58 UTC
**1. # export JAVA_TOOL_OPTIONS="-Dhttps.protocols=TLSv1.2"** <-- to fix the HTTPS issues 
**2. rmiscout# ./gradlew shadowJar** <-- to be checked the following errors 
Picked up JAVA_TOOL_OPTIONS: -Dhttps.protocols=TLSv1.2

**FAILURE:** Build failed with an exception.

* Where:
Build file '/root/rmiscout/build.gradle' line: 4

* What went wrong:
Plugin [id: 'com.github.johnrengelman.shadow', version: '2.0.4'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.github.johnrengelman.shadow:com.github.johnrengelman.shadow.gradle.plugin:2.0.4')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 0s

**Comment by the-bumble** [comment] 2020-06-04 19:27
Hi alt3kx,

Hmmm... I'm not able to reproduce this one (I tried a variety of JDK versions). It appears the JDK configuration you are using is not enabling TLSv1.2 by default or has been modified. As best I understand, it's been the default for a while (https://blogs.oracle.com/java-platform-group/jdk-8-will-use-tls-12-as-default). See: https://github.com/gradle/gradle/issues/5940. It looks like beta/EA JDK builds set odd defaults. 

Alternatively, here is a basic working Docker image:

```Dockerfile
FROM openjdk:8
COPY . /rmiscout
WORKDIR /rmiscout
RUN ./gradlew shadowJar
ENTRYPOINT ["./rmiscout.sh"]
CMD ["-h"]
```
Let me know if you think it's a bug with rmiscout gradle configuration or a JDK configuration issue.

Thank you!

**Comment by the-bumble** [comment] 2020-06-11 15:33
Closing this issue as it appears to be a local JDK configuration issue. Thanks for the report!

**Closed by the-bumble** 2020-06-11 15:33 UTC
